version: "3"
services:
  # elasticsearch:
  #   image: elasticsearch:7.5.1
  #   restart: always
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  #   tty: true
  #   environment:
  #     discovery.type: single-node

  mongodb0:
    image: mongo:3.6
    restart: always
    command: --replSet "rs0"
    ports:
      - "27017:27017"

  mongodb1:
    image: mongo:3.6
    restart: always
    command: --replSet "rs0"
    ports:
      - "27018:27017"

  mongosetup:
    build: ./mongo-setup-replication

# mongoconnector:
#   build: ./mongoconnector
#   links:
#     - "mongodb0"

volumes:
  es-data:
    driver: local
