# This will start 5 nodes:
# mongo will server as the only member of the cluster
# mongosetup will init mongo as the master node
# elasticsearch will server as the index search db
# kibana will server as the web ui of elasticsearch
# mongo-connector will pipeline mongodb content to the elasticsearch

# mongosetup:
#   build: ./mongosetup
#   mem_limit: 1024m
#   links:
#     - mongo:mongo

# kibana:
#   image: kibana:4.1
#   ports:
#     - "5601:5601"
#   links:
#     - elasticsearch:elasticsearch

# mongoconnector:
#   build: ./mongoconnector
#   links:
#     - elasticsearch:elasticsearch
#     - mongo:mongo

version: "0.1"
services:
  elasticsearch:
    image: elasticsearch:7.5.1
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      discovery.type: single-node

  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"

volumes:
  es-data:
    driver: local
